//! Multiway equity.
use crate::monte_carlo::monte_carlo_multiway;
use poker_eval::evaluate_7card;
use poker_types::Card;
#[derive(Debug, Clone, PartialEq)]
pub struct MultiwayResult { pub equities: Vec<f64>, pub total_outcomes: u64 }
pub fn multiway_exact(hands: &[Vec<Card>], board: &[Card]) -> MultiwayResult { let rem = 5 - board.len(); let mut known = std::collections::HashSet::new(); for h in hands { for c in h { known.insert(c.index()); } } for c in board { known.insert(c.index()); } let mut avail = Vec::with_capacity(52 - known.len()); for rank in poker_types::Rank::ALL { for suit in poker_types::Suit::ALL { let c = Card::new(rank, suit); if !known.contains(&c.index()) { avail.push(c); } } } let np = hands.len(); let mut wc = vec![0u64; np]; let mut tc = vec![0u64; np]; if rem == 0 { let mut br = 0u32; let mut winners = Vec::new(); for (i, h) in hands.iter().enumerate() { let mut c = Vec::with_capacity(7); c.extend_from_slice(h); c.extend_from_slice(board); let r = evaluate_7card(&c); if r > br { br = r; winners.clear(); winners.push(i); } else if r == br { winners.push(i); } } if winners.len() == 1 { wc[winners[0]] = 1; } else { for &i in &winners { tc[i] = 1; } } } else if rem == 1 { for &c in &avail { mws(hands, board, &[c], &mut wc, &mut tc); } } else if rem == 2 { let n = avail.len(); for i in 0..n { for j in (i+1)..n { mws(hands, board, &[avail[i], avail[j]], &mut wc, &mut tc); } } } else { let mc = monte_carlo_multiway(hands, board, 50000); return MultiwayResult { equities: mc.equities, total_outcomes: mc.total_simulations }; } let total: u64 = wc.iter().sum::<u64>() + tc.iter().sum::<u64>(); let eq = (0..np).map(|i| wc[i] as f64 / total as f64 + if total > 0 { tc[i] as f64 / total as f64 / 2.0 } else { 0.0 }).collect(); MultiwayResult { equities: eq, total_outcomes: total } }
fn mws(hands: &[Vec<Card>], board: &[Card], runout: &[Card], wc: &mut [u64], tc: &mut [u64]) { let mut br = 0u32; let mut winners = Vec::new(); for (i, h) in hands.iter().enumerate() { let mut c = Vec::with_capacity(7); c.extend_from_slice(h); c.extend_from_slice(board); c.extend_from_slice(runout); let r = evaluate_7card(&c); if r > br { br = r; winners.clear(); winners.push(i); } else if r == br { winners.push(i); } } if winners.len() == 1 { wc[winners[0]] += 1; } else { for &i in &winners { tc[i] += 1; } } }
#[cfg(test)]
mod tests { use super::*; fn p(s: &str) -> Vec<Card> { Card::parse_many(s).unwrap() } #[test] fn test_three() { let h = vec![p("AsAd"), p("KsKd"), p("QdQc")]; let r = multiway_exact(&h, &[]); assert_eq!(r.equities.len(), 3); assert!(r.equities[0] > r.equities[1]); assert!(r.equities[1] > r.equities[2]); } }